ALTER TABLE "tarefa_checklist_items" ADD COLUMN "grupo" text DEFAULT 'Checklist' NOT NULL;--> statement-breakpoint
ALTER TABLE "tarefas" ADD COLUMN "descricao" text;--> statement-breakpoint
ALTER TABLE "tarefas" ADD COLUMN "etiquetas" jsonb;--> statement-breakpoint
ALTER TABLE "tarefas" ADD COLUMN "tempo_estimado" text;--> statement-breakpoint
ALTER TABLE "tarefas" ADD COLUMN "data_inicio" date;--> statement-breakpoint
ALTER TABLE "tarefas" ADD COLUMN "codigo_num" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "tarefas_codigo_num_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "tarefas" ADD COLUMN "codigo" text GENERATED ALWAYS AS ('TAR-' || lpad(codigo_num::text, 4, '0')) STORED;--> statement-breakpoint
CREATE UNIQUE INDEX "tarefas_codigo_idx" ON "tarefas" USING btree ("codigo");